from application import db 
from flask import current_app
# from itsdangerous import URLSafeTimedSerializer as Serializer # type: ignore
from itsdangerous import URLSafeTimedSerializer as Serializer 
from flask_login import UserMixin # type: ignore
from sqlalchemy.sql import func # type: ignore
from datetime import datetime


class CaseStudyAnalysis(db.Model):
    CSA_id = db.Column(db.Integer, primary_key=True)
    CSA_participant_id = db.Column(db.Integer, db.ForeignKey('participants.p_id'))  # Corrected to db.Integer and table name
    CSA_assessor_id = db.Column(db.Integer, db.ForeignKey('assessor.a_id'))
    # 1st page 
    CSA_BringsPerspectiveAndTeaches_Q = db.Column(db.String(450))
    CSA_BringsPerspectiveAndTeaches_v = db.Column(db.Integer) 
    CSA_BringsPerspectiveAndTeaches_la = db.Column(db.String(850)) 
    CSA_Resolve_Business_Challenges_Q = db.Column(db.String(450))
    CSA_Resolve_Business_Challenges_v = db.Column(db.Integer)
    CSA_Resolve_Business_Challenges_la = db.Column(db.String(900)) 
    CSA_Iterate_For_Outcomes_Q = db.Column(db.String(450))
    CSA_Iterate_For_Outcomes_v = db.Column(db.Integer)
    CSA_Iterate_For_Outcomes_la = db.Column(db.String(900)) 
    CSA_Address_Complex_Issues_Q = db.Column(db.String(450))
    CSA_Address_Complex_Issues_v = db.Column(db.Integer)
    CSA_Address_Complex_Issues_la = db.Column(db.String(900)) 
    # 2nd page 
    CSA_Share_Market_Insights_Q = db.Column(db.String(450))
    CSA_Share_Market_Insights_v = db.Column(db.Integer)
    CSA_Share_Market_Insights_la = db.Column(db.String(900)) 
    CSA_Create_Customer_Experience_Plans_Q = db.Column(db.String(450))
    CSA_Create_Customer_Experience_Plans_v = db.Column(db.Integer)
    CSA_Create_Customer_Experience_Plans_la = db.Column(db.String(900))
    CSA_Connect_Teams_For_Solutions_Q = db.Column(db.String(450))
    CSA_Connect_Teams_For_Solutions_v = db.Column(db.Integer)
    CSA_Connect_Teams_For_Solutions_la = db.Column(db.String(900))
    CSA_Develop_Engagement_Plan_Q = db.Column(db.String(450))
    CSA_Develop_Engagement_Plan_v = db.Column(db.Integer) 
    CSA_Develop_Engagement_Plan_la = db.Column(db.String(900))
    # 3rd field 
    CSA_Demonstrate_Business_Knowledge_Q = db.Column(db.String(450))
    CSA_Demonstrate_Business_Knowledge_v = db.Column(db.Integer)
    CSA_Demonstrate_Business_Knowledge_la =db.Column(db.String(900))
    CSA_Calculated_Risk_Taking_Q = db.Column(db.String(450))
    CSA_Calculated_Risk_Taking_v = db.Column(db.Integer) 
    CSA_Calculated_Risk_Taking_la = db.Column(db.String(900))
    CSA_Enterprise_Mindset_Q = db.Column(db.String(450))
    CSA_Enterprise_Mindset_v = db.Column(db.Integer)
    CSA_Enterprise_Mindset_la = db.Column(db.String(900))
    CSA_Proactive_Decision_Making_Q = db.Column(db.String(450))
    CSA_Proactive_Decision_Making_v = db.Column(db.Integer)
    CSA_Proactive_Decision_Making_la = db.Column(db.String(900))
    # 4th page 
    CSA_Explain_Purpose_And_Actions_Q = db.Column(db.String(450))
    CSA_Explain_Purpose_And_Actions_v =  db.Column(db.Integer)
    CSA_Explain_Purpose_And_Actions_la =db.Column(db.String(900))
    CSA_Set_Specific_Team_Objectives_Q = db.Column(db.String(450))
    CSA_Set_Specific_Team_Objectives_v = db.Column(db.Integer)
    CSA_Set_Specific_Team_Objectives_la =db.Column(db.String(900))
    CSA_Priority_Management_Q = db.Column(db.String(450))
    CSA_Priority_Management_v = db.Column(db.Integer)
    CSA_Priority_Management_la =db.Column(db.String(900))
    CSA_Ensure_Cross_Functional_Alignment_Q = db.Column(db.String(450)) 
    CSA_Ensure_Cross_Functional_Alignment_v = db.Column(db.Integer)
    CSA_Ensure_Cross_Functional_Alignment_la =db.Column(db.String(900))
    
class GroupDiscussion(db.Model):
    GD_id = db.Column(db.Integer, primary_key=True)
    GD_participant_id = db.Column(db.Integer, db.ForeignKey('participants.p_id'))  # Corrected to db.Integer and table name
    GD_assessor_id = db.Column(db.Integer, db.ForeignKey('assessor.a_id')) 
    # 1st page 
    GD_ExplainsPurposeandWhy_Q = db.Column(db.String(450))
    GD_ExplainsPurposeandWhy_v = db.Column(db.Integer)
    GD_ExplainsPurposeandWhy_la = db.Column(db.String(900)) 
    GD_SetsTeamObjectives_Q = db.Column(db.String(450))
    GD_SetsTeamObjectives_v = db.Column(db.Integer)
    GD_SetsTeamObjectives_la = db.Column(db.String(900))
    GD_PriorityManagement_Q = db.Column(db.String(450))
    GD_PriorityManagement_v = db.Column(db.Integer)
    GD_PriorityManagement_la = db.Column(db.String(850))
    GD_CrossFunctionalAlignment_Q = db.Column(db.String(450))
    GD_CrossFunctionalAlignment_v = db.Column(db.Integer)
    GD_CrossFunctionalAlignment_la = db.Column(db.String(900))
    # 2nd page
    GD_DifficultEmotionalConversations_Q = db.Column(db.String(450))
    GD_DifficultEmotionalConversations_v = db.Column(db.Integer)
    GD_DifficultEmotionalConversations_la = db.Column(db.String(900))
    GD_TurnDifficultConversationsintoAction_Q = db.Column(db.String(450))
    GD_TurnDifficultConversationsintoAction_v = db.Column(db.Integer)
    GD_TurnDifficultConversationsintoAction_la = db.Column(db.String(900))
    GD_TranslateintoFunctionalPlans_Q = db.Column(db.String(450))
    GD_TranslateintoFunctionalPlans_v = db.Column(db.Integer)
    GD_TranslateintoFunctionalPlans_la = db.Column(db.String(900))
    GD_UtilizesEffectiveCommunicationtoDeescalateEmotionally_Q = db.Column(db.String(450)) 
    GD_UtilizesEffectiveCommunicationtoDeescalateEmotionally_v = db.Column(db.Integer)
    GD_UtilizesEffectiveCommunicationtoDeescalateEmotionally_la = db.Column(db.String(900))
    # 3rd page 
    GD_StandsupforOwnRights_Q = db.Column(db.String(450))
    GD_StandsupforOwnRights_v = db.Column(db.Integer)
    GD_StandsupforOwnRights_la = db.Column(db.String(900))
    GD_ProactiveConversationPlanning_Q = db.Column(db.String(450))
    GD_ProactiveConversationPlanning_v = db.Column(db.Integer)
    GD_ProactiveConversationPlanning_la = db.Column(db.String(900))
    GD_OpenCommunicationEnvironment_Q = db.Column(db.String(450))
    GD_OpenCommunicationEnvironment_v = db.Column(db.Integer)
    GD_OpenCommunicationEnvironment_la = db.Column(db.String(900))
    GD_AssertivenessGraceandValidation_Q = db.Column(db.String(450))
    GD_AssertivenessGraceandValidation_v = db.Column(db.Integer)
    GD_AssertivenessGraceandValidation_la = db.Column(db.String(900))
    # 4th page 
    GD_MeetingImmediatewithStrategy_Q = db.Column(db.String(450))
    GD_MeetingImmediatewithStrategy_v = db.Column(db.Integer)
    GD_MeetingImmediatewithStrategy_la = db.Column(db.String(900))
    GD_ForwardThinkingAgenda_Q = db.Column(db.String(450))
    GD_ForwardThinkingAgenda_v = db.Column(db.Integer)
    GD_ForwardThinkingAgenda_la = db.Column(db.String(900))   
    GD_EnsuringActionsStrategyAlignment_Q = db.Column(db.String(450))
    GD_EnsuringActionsStrategyAlignment_v = db.Column(db.Integer)
    GD_EnsuringActionsStrategyAlignment_la = db.Column(db.String(900))
       
class CaseStudyPresentation(db.Model):
    CSP_id = db.Column(db.Integer, primary_key=True)
    CSP_participant_id = db.Column(db.Integer, db.ForeignKey('participants.p_id'))  # Corrected to db.Integer and table name
    CSP_assessor_id = db.Column(db.Integer, db.ForeignKey('assessor.a_id'))
    # 1st page 
    CSP_difficult_situations_articulation_Q = db.Column(db.String(450))
    CSP_difficult_situations_articulation_v = db.Column(db.Integer)
    CSP_difficult_situations_articulation_la = db.Column(db.String(900)) 
    CSP_effective_response_to_challenges_Q = db.Column(db.String(450))
    CSP_effective_response_to_challenges_v = db.Column(db.Integer)
    CSP_effective_response_to_challenges_la = db.Column(db.String(900))
    CSP_presentation_clarity_confidence_Q = db.Column(db.String(450))
    CSP_presentation_clarity_confidence_v = db.Column(db.Integer)
    CSP_presentation_clarity_confidence_la = db.Column(db.String(900))
    CSP_composure_during_presentations_Q = db.Column(db.String(450))
    CSP_composure_during_presentations_v = db.Column(db.Integer)
    CSP_composure_during_presentations_la = db.Column(db.String(900))
    # 2nd page 
    CSP_opinions_sharing_with_evidence_Q = db.Column(db.String(450))
    CSP_opinions_sharing_with_evidence_v = db.Column(db.Integer)
    CSP_opinions_sharing_with_evidence_la = db.Column(db.String(900))
    CSP_well_defined_ideas_advocacy_Q = db.Column(db.String(450))
    CSP_well_defined_ideas_advocacy_v = db.Column(db.Integer)
    CSP_well_defined_ideas_advocacy_la = db.Column(db.String(900))
    CSP_persuasion_without_coercion_Q = db.Column(db.String(450))
    CSP_persuasion_without_coercion_v = db.Column(db.Integer)
    CSP_persuasion_without_coercion_la = db.Column(db.String(900))
    # 3rd page 
    CSP_balance_of_time_aspects_Q = db.Column(db.String(450))
    CSP_balance_of_time_aspects_v = db.Column(db.Integer)
    CSP_balance_of_time_aspects_la = db.Column(db.String(900))
    CSP_trend_identification_time_allocation_Q = db.Column(db.String(450))
    CSP_trend_identification_time_allocation_v = db.Column(db.Integer)
    CSP_trend_identification_time_allocation_la = db.Column(db.String(900))
    CSP_high_impact_presentation_execution_Q = db.Column(db.String(450))
    CSP_high_impact_presentation_execution_v = db.Column(db.Integer)
    CSP_high_impact_presentation_execution_la = db.Column(db.String(900))
    
class InboxActivity(db.Model):
    IA_id = db.Column(db.Integer, primary_key=True)
    IA_participant_id = db.Column(db.Integer, db.ForeignKey('participants.p_id'))  # Corrected to db.Integer and table name
    IA_assessor_id = db.Column(db.Integer, db.ForeignKey('assessor.a_id'))
    # 1st page
    IA_ShareAndTranslateMarketInsights_Q =db.Column(db.String(400))
    IA_ShareAndTranslateMarketInsights_v = db.Column(db.Integer)
    IA_ShareAndTranslateMarketInsights_la = db.Column(db.String(900))
    IA_CreatesPlanstoDeliverDifferentiatedCustomerExperiences_Q =db.Column(db.String(400))
    IA_CreatesPlanstoDeliverDifferentiatedCustomerExperiences_v = db.Column(db.Integer)
    IA_CreatesPlanstoDeliverDifferentiatedCustomerExperiences_la = db.Column(db.String(900))
    IA_ConnectsTeamswithSharedCustomerGoalstoDeliver_Q =db.Column(db.String(400))
    IA_ConnectsTeamswithSharedCustomerGoalstoDeliver_v = db.Column(db.Integer)
    IA_ConnectsTeamswithSharedCustomerGoalstoDeliver_la = db.Column(db.String(900))
    IA_Setsupanengagementplancollaborateswithstakeholders_Q =db.Column(db.String(400))
    IA_Setsupanengagementplancollaborateswithstakeholders_v = db.Column(db.Integer)
    IA_Setsupanengagementplancollaborateswithstakeholders_la = db.Column(db.String(900))
    # 2nd page
    IA_PositiveAuthenticityCourage_Q = db.Column(db.String(400))
    IA_PositiveAuthenticityCourage_v = db.Column(db.Integer) 
    IA_PositiveAuthenticityCourage_la = db.Column(db.String(900))
    IA_TalentPlanningGroomingAndDiverseStrongPipelines_Q = db.Column(db.String(400))
    IA_TalentPlanningGroomingAndDiverseStrongPipelines_v = db.Column(db.Integer) 
    IA_TalentPlanningGroomingAndDiverseStrongPipelines_la = db.Column(db.String(900))
    IA_FostersLearningAndHealthyWorkClimate_Q = db.Column(db.String(400))
    IA_FostersLearningAndHealthyWorkClimate_v = db.Column(db.Integer)
    IA_FostersLearningAndHealthyWorkClimate_la = db.Column(db.String(900))
    IA_TalentPlanningDiverseStrongPipelinesOutside_Q = db.Column(db.String(400))
    IA_TalentPlanningDiverseStrongPipelinesOutside_v = db.Column(db.Integer)
    IA_TalentPlanningDiverseStrongPipelinesOutside_la = db.Column(db.String(850))
    # 3rd page
    IA_CollaboratesAndConnects_Q = db.Column(db.String(400))
    IA_CollaboratesAndConnects_v = db.Column(db.Integer)
    IA_CollaboratesAndConnects_la = db.Column(db.String(900))
    IA_BringPerspectiveandTeachesProfiecinet_Q = db.Column(db.String(400))
    IA_BringPerspectiveandTeachesProfiecinet_v = db.Column(db.Integer) 
    IA_BringPerspectiveandTeachesProfiecinet_la = db.Column(db.String(900))
    IA_MultipleSourceOfInput_Q = db.Column(db.String(400))
    IA_MultipleSourceOfInput_v = db.Column(db.Integer)
    IA_MultipleSourceOfInput_la = db.Column(db.String(900))
    IA_IteratesForBestOutcomes_Q = db.Column(db.String(400))
    IA_IteratesForBestOutcomes_v = db.Column(db.Integer) 
    IA_IteratesForBestOutcomes_la = db.Column(db.String(900))
    IA_CourageousConversation_Q = db.Column(db.String(400))
    IA_CourageousConversation_v = db.Column(db.Integer)
    IA_CourageousConversation_la = db.Column(db.String(900))
    # 4th field
    IA_StandsUpForOwnRights_Q = db.Column(db.String(400)) 
    IA_StandsUpForOwnRights_v = db.Column(db.Integer)
    IA_StandsUpForOwnRights_la = db.Column(db.String(900)) 
    IA_AbelToShareOpinionsAndViews_Q = db.Column(db.String(400))
    IA_AbelToShareOpinionsAndViews_v = db.Column(db.Integer)
    IA_AbelToShareOpinionsAndViews_la = db.Column(db.String(900)) 
    IA_SaysNoCourageouslyAgreeandDisagrees_Q = db.Column(db.String(400))
    IA_SaysNoCourageouslyAgreeandDisagrees_v = db.Column(db.Integer)
    IA_SaysNoCourageouslyAgreeandDisagrees_la = db.Column(db.String(900)) 
    IA_PossessesWellDefinedIdeasAndOpinions_Q = db.Column(db.String(400))
    IA_PossessesWellDefinedIdeasAndOpinions_v = db.Column(db.Integer)
    IA_PossessesWellDefinedIdeasAndOpinions_la = db.Column(db.String(900))  
    IA_UseseveralTechndependonPersonality_Q = db.Column(db.String(400))
    IA_UseseveralTechndependonPersonality_v = db.Column(db.Integer)
    IA_UseseveralTechndependonPersonality_la = db.Column(db.String(900))
    
class RolePlay(db.Model):
    RP_id = db.Column(db.Integer, primary_key=True)
    RP_participant_id = db.Column(db.Integer, db.ForeignKey('participants.p_id'))  # Corrected to db.Integer and table name
    RP_assessor_id = db.Column(db.Integer, db.ForeignKey('assessor.a_id'))
    # 1st page 
    RP_PositiveAuthenticityAndCourage_Q = db.Column(db.String(450))
    RP_PositiveAuthenticityAndCourage_v = db.Column(db.Integer)
    RP_PositiveAuthenticityAndCourage_la = db.Column(db.String(900))
    RP_TalentPlanningAndDiverseStrongPipelines_Q = db.Column(db.String(450))
    RP_TalentPlanningAndDiverseStrongPipelines_v = db.Column(db.Integer)
    RP_TalentPlanningAndDiverseStrongPipelines_la = db.Column(db.String(900))
    RP_CollaboratesAndConnects_Q = db.Column(db.String(450))
    RP_CollaboratesAndConnects_v = db.Column(db.Integer)
    RP_CollaboratesAndConnects_la = db.Column(db.String(900))
    # 2nd page 
    RP_DeepBusinessKnowledge_Q = db.Column(db.String(450))
    RP_DeepBusinessKnowledge_v = db.Column(db.Integer)
    RP_DeepBusinessKnowledge_la = db.Column(db.String(900))
    RP_CalculatedRiskTaking_Q = db.Column(db.String(450))
    RP_CalculatedRiskTaking_v = db.Column(db.Integer)
    RP_CalculatedRiskTaking_la = db.Column(db.String(900))
    RP_EnterpriseMindset_Q = db.Column(db.String(450))
    RP_EnterpriseMindset_v = db.Column(db.Integer)
    RP_EnterpriseMindset_la = db.Column(db.String(900))
    RP_ProactiveDecisionMaking_Q = db.Column(db.String(450))
    RP_ProactiveDecisionMaking_v =  db.Column(db.Integer)
    RP_ProactiveDecisionMaking_la = db.Column(db.String(900))
    RP_EnablesDecisionMaking_Q = db.Column(db.String(450))
    RP_EnablesDecisionMaking_v = db.Column(db.Integer)
    RP_EnablesDecisionMaking_la = db.Column(db.String(900))
    # 3rd page 
    RP_Recognizesthroleofopinionsandstakes_Q = db.Column(db.String(450))
    RP_Recognizesthroleofopinionsandstakes_v = db.Column(db.Integer)
    RP_Recognizesthroleofopinionsandstakes_la = db.Column(db.String(900))
    RP_Abletoturndifficultconversationintoaction_Q = db.Column(db.String(450))
    RP_Abletoturndifficultconversationintoaction_v = db.Column(db.Integer)
    RP_Abletoturndifficultconversationintoaction_la = db.Column(db.String(900))
    RP_maintaincomposureindifficultsituations_Q = db.Column(db.String(450))
    RP_maintaincomposureindifficultsituations_v = db.Column(db.Integer)
    RP_maintaincomposureindifficultsituations_la = db.Column(db.String(900))
    # 4th page 
    RP_BalancingShorttermandLongtermGoals_Q = db.Column(db.String(450))
    RP_BalancingShorttermandLongtermGoals_v = db.Column(db.Integer)
    RP_BalancingShorttermandLongtermGoals_la = db.Column(db.String(900))
    RP_StrategicAlignment_Q = db.Column(db.String(450))
    RP_StrategicAlignment_v = db.Column(db.Integer)
    RP_StrategicAlignment_la = db.Column(db.String(900))
    RP_RecognizePatternandTrends_Q = db.Column(db.String(450))
    RP_RecognizePatternandTrends_v = db.Column(db.Integer)
    RP_RecognizePatternandTrends_la = db.Column(db.String(900))
    RP_AbletoAllocateRes_Q = db.Column(db.String(450))
    RP_AbletoAllocateRes_v = db.Column(db.Integer)
    RP_AbletoAllocateRes_la = db.Column(db.String(900))

class CBI(db.Model):
    CBI_id = db.Column(db.Integer, primary_key=True)
    CBI_participant_id = db.Column(db.Integer, db.ForeignKey('participants.p_id'))  # Corrected to db.Integer and table name
    CBI_assessor_id = db.Column(db.Integer, db.ForeignKey('assessor.a_id'))
   #1st page
    CBI_Gather_Market_Insights_Action_Q = db.Column(db.String(450))
    CBI_Gather_Market_Insights_Action_v = db.Column(db.Integer)
    CBI_Gather_Market_Insights_Action_la = db.Column(db.String(500))
    CBI_Address_Customer_Complaint_Action_Q = db.Column(db.String(450))
    CBI_Address_Customer_Complaint_Action_v = db.Column(db.Integer)
    CBI_Address_Customer_Complaint_Action_la = db.Column(db.String(500))
    CBI_Anticipate_Customer_Needs_Solution_Q = db.Column(db.String(450))
    CBI_Anticipate_Customer_Needs_Solution_v = db.Column(db.Integer)
    CBI_Anticipate_Customer_Needs_Solution_la = db.Column(db.String(500))
    #2nd page
    CBI_Identify_Talent_Networks_Use_Q = db.Column(db.String(450))
    CBI_Identify_Talent_Networks_Use_v = db.Column(db.Integer)
    CBI_Identify_Talent_Networks_Use_la = db.Column(db.String(500))
    CBI_Nurture_Develop_Talent_Approach_Q = db.Column(db.String(450))
    CBI_Nurture_Develop_Talent_Approach_v = db.Column(db.Integer)
    CBI_Nurture_Develop_Talent_Approach_la = db.Column(db.String(500))
    CBI_Collaborate_Create_Work_Climate_Q = db.Column(db.String(450)) 
    CBI_Collaborate_Create_Work_Climate_v = db.Column(db.Integer)
    CBI_Collaborate_Create_Work_Climate_la = db.Column(db.String(500))
    #3rd page
    CBI_Bring_Perspectives_Challenging_Problem_Q = db.Column(db.String(450))
    CBI_Bring_Perspectives_Challenging_Problem_v = db.Column(db.Integer)
    CBI_Bring_Perspectives_Challenging_Problem_la = db.Column(db.String(500))
    CBI_Gather_Input_Solve_Problem_Q = db.Column(db.String(450))
    CBI_Gather_Input_Solve_Problem_v = db.Column(db.Integer)
    CBI_Gather_Input_Solve_Problem_la = db.Column(db.String(500))
    CBI_Courageous_Conversations_Outcomes_Q = db.Column(db.String(450))
    CBI_Courageous_Conversations_Outcomes_v = db.Column(db.Integer)
    CBI_Courageous_Conversations_Outcomes_la = db.Column(db.String(500))
    #4th page
    CBI_Business_Understanding_Influence_Decision_Q = db.Column(db.String(450))
    CBI_Business_Understanding_Influence_Decision_v = db.Column(db.Integer)
    CBI_Business_Understanding_Influence_Decision_la = db.Column(db.String(500))
    CBI_Calculated_Risk_Taking_Outcome_Q = db.Column(db.String(450))
    CBI_Calculated_Risk_Taking_Outcome_v = db.Column(db.Integer)
    CBI_Calculated_Risk_Taking_Outcome_la = db.Column(db.String(500))
    CBI_Proactive_Decision_Impact_Q = db.Column(db.String(450))    
    CBI_Proactive_Decision_Impact_v = db.Column(db.Integer)
    CBI_Proactive_Decision_Impact_la = db.Column(db.String(500))
    CBI_Enable_Close_Decision_Making_Q = db.Column(db.String(450))
    CBI_Enable_Close_Decision_Making_v = db.Column(db.Integer)
    CBI_Enable_Close_Decision_Making_la = db.Column(db.String(500))
